GET https://api.themoviedb.org/3/search/tv?query=the+residence
Accept: application/json
Authorization: Bearer {{tmdbAccessToken}}

###
GET https://api.themoviedb.org/3/tv/242054
Accept: application/json
Authorization: Bearer {{tmdbAccessToken}}

###
GET https://api.themoviedb.org/3/tv/242054/season/1
Accept: application/json
Authorization: Bearer {{tmdbAccessToken}}

